import Route from '@ioc:Adonis/Core/Route'

Route.group(() => {
  Route.get('/users', 'Api/v1/UsersController.index')
  Route.post('/users', 'Api/v1/UsersController.create')
  Route.post('/login', 'Api/v1/AuthController.login')
  Route.post('/logout', 'Api/v1/AuthController.logout')
  Route.get('/groups', 'Api/v1/GroupsController.index')
  Route.post('/groups', 'Api/v1/GroupsController.create')
  Route.get('/devices', 'Api/v1/DevicesController.index')
  Route.post('/devices', 'Api/v1/DevicesController.create')
  Route.get('/devices/:alias', 'Api/v1/DevicesController.show')
  Route.get('/orders', 'Api/v1/OrdersController.index').middleware('auth')
  Route.post('/orders', 'Api/v1/OrdersController.create')
  Route.get('/orders/:code', 'Api/v1/OrdersController.show')
  Route.post('/orders/payments', 'Api/v1/OrdersPaymentsController.create')
  Route.post('/orders/charges', 'Api/v1/OrdersChargesController.create')
  Route.delete('/orders/charges/:id', 'Api/v1/OrdersChargesController.delete')
  Route.get('/clients', 'Api/v1/ClientsController.index')
  Route.post('/clients', 'Api/v1/ClientsController.create')
  Route.delete('/clients/:id', 'Api/v1/ClientsController.delete')
  Route.patch('/orders/:code/status/:status', 'Api/v1/OrdersController.updateStatus')
}).prefix('/api/v1')
